### ISSUE TITLE
chore(deps-major) Update dependency @mui/x-date-pickers to v6

### ISSUE THREAD

**Issue by ansmonjol** [getlago/lago-front#1228]

**Comment by InsaneNaman** [comment]
Hey team, I was trying to play around this issue and have already followed this wiki to do the [local setup](https://github.com/getlago/lago/wiki/Development-Environment). The local environment is up and running but I am not sure about the afterwards. I created a test account using `signup` page and when I am trying to login with the same creds, I am facing this `Unauthorized` error. Is there any default credential or can you please pin point my mistake?

<img width="1563" alt="image" src="https://github.com/getlago/lago-front/assets/13780776/467382e4-c2db-4a82-95f2-8b3a96c77ad3">

**Comment by InsaneNaman** [comment]
Hey @ansmonjol, I understand you must be busy. Just want to leave a friendly nudge over here. :D

**Comment by ansmonjol** [comment]
Hey @InsaneNaman sorry I haven't saw your comment!

Like that, I could not really tell why it happen. There could be an issue in your setup that lead to this situation.
For a better support you can join our [Slack community](https://www.getlago.com/slack) and post your questions on the #need-help channel! 

Side note, we used to have a similar issue that has been fixed. Which version of Lago are you using right now?

**Comment by ansmonjol** [comment]
BTW, I'll push a branch for this v6 transition. I'm almost done with the migration but I need to fix some UI elements on this component using the v6. API heavily changed and many stuffs needs to be adapted
