### ISSUE TITLE
[QA] Support 5 decimal for charges

### ISSUE THREAD

**Issue by michaelponrajah** [getlago/lago-front#135]
- [x] When I'm adding a gradutated charge with or without decimal, I can't Create my Plan
https://user-images.githubusercontent.com/82527978/170704901-e18e8afe-a870-4265-a7f1-52ba1b7339b6.mp4

**Comment by MorganeLecurieux** [comment]
Closed by https://github.com/getlago/lago-front/commit/9acd01a4a81a669068d6e24e44e1745cb180e925
