### ISSUE TITLE
[BUG] doubled scrollbars on currency dropdown/select

### ISSUE THREAD

**Issue by prognostikos** [getlago/lago-front#138]
**Describe the bug**

Doubled scrollbars in currency dropdown/select

**To Reproduce**

Go to add a new plan. Click on the currency code. Observe that two scrollbars are shown and the full currency code is obscured.

**Expected behavior**

The dropdown should be shown without the double scrollbars and the full currency code should be visible.

**Screenshots**

![image](https://user-images.githubusercontent.com/515254/171844188-cb0efd9d-d5cd-4ae0-8cfe-cfc51d62c5ad.png)

**Additional context**

**Comment by MorganeLecurieux** [comment]
Note : Bug reproduced on Safari
