### ISSUE TITLE
[BUG] While adding a new customer, clicking into the body of the page by accident and dismissing the sidebar should not erase all progress

### ISSUE THREAD

**Issue by doctorpangloss** [getlago/lago-front#1475]
**Describe the bug**
Clicking into the shaded area by accident while adding data into the sidebars and losing the in-progress work is a huge nuisance.

**To Reproduce**
1. Navigate to the Customers route (`/customers`)
2. Click Add a customer.
3. Observe the sidebar form opens.
4. Add some data.
5. Click into the shaded area.
6. Click add a customer again.
7. Observe the data is erased. It should not be.

**Expected behavior**
You should retain the in-progress data since it's very easy to accidentally click into the shaded area.

**Environment infos**

**App environment :** production
**API URL :** https://xxx
**Version :** 1.0.0 (it's actually 1.2.1)
**User Id :** 52e9cbc7-69dd-4f26-b44c-38df742498d5

**Comment by ansmonjol** [comment]
Hey @doctorpangloss,

Thanks a lot for reporting this. It is indeed a very frustrating case.

Adding a confirm modal in case of "click away", if some data are not saved and user clicks away, would suit your needs and keep consistency over the app. We have similar behaviour in some forms.

I'll try to allocate time on this topic in the coming weeks.

**Comment by ansmonjol** [comment]
Fix have been merged, it will be available on next release.

Thanks for reporting this
