### ISSUE TITLE
[BUG] When adding a new customer and setting up a Stripe connection, the site should poll for new potential Stripe connections whenever the user interacts with the dropdown

### ISSUE THREAD

**Issue by doctorpangloss** [getlago/lago-front#1476]
**Describe the bug**
Adding a stripe connection in another page should make it appear in the dropdown.

In general, the forms should do a better job retaining information as you interact with the site.

**To Reproduce**
1. Visit the `/customers` route
2. Add a customer
3. Navigate down to Payment provider information.
4. Click default payment provider: stripe
5. Observe no connected accounts.
6. Open a new tab, configure a Stripe account.
7. Observe that the connected accounts dropdown is not updated. It should be.

**Expected behavior**
Update the dropdown as soon as a connected account is added or the user interacts with the dropdown.

**Environment infos**
### Environment informations
**App environment :** production
**API URL :** xxx
**Version :** 1.0.0 (really 1.2.1)
**User Id :** 52e9cbc7-69dd-4f26-b44c-38df742498d5

**Comment by ansmonjol** [comment]
This part of the app will very soon be refactored.

I'll have this case in mind during implementation.

Thanks for reporting

**Comment by ansmonjol** [comment]
This will be fixed by https://github.com/getlago/lago-front/pull/1463

Payment integration will be fetched each time you open the  accordion - the one dedicated to selecting the Stripe (or other PP) linked account.
