### ISSUE TITLE
[BUG] From the invoices route, seeing "Assign a plan to a customer to create invoices" even though a plan is assigned to a customer

### ISSUE THREAD

**Issue by doctorpangloss** [getlago/lago-front#1477]
**Describe the bug**
> Assign a plan to a customer to create invoices...
Appears when visiting `/invoices` despite a plan assigned to a customer.

**To Reproduce**
1. Create a customer.
2. Create a plan.
3. Assign the plan to the customer. The subscription starts more than 1 month ago.
4. Visit `/invoices`
5. Observe `Assign a plan to a customer to create invoices...`. This should instead allow the user to create an invoice for the past invoices.

**Expected behavior**
I should be able to create an invoice now that a plan is assigned to a customer.

**Environment infos**

**App environment :** production
**API URL :** xxx
**Version :** 1.0.0 (really 1.2.1)
**User Id :** 52e9cbc7-69dd-4f26-b44c-38df742498d5

**Comment by ansmonjol** [comment]
Good point! 

Probably a wording that mentions the "the end of billing period" or "using add-ons"  would suit better this part of the app.
We have similar one in`users/:id/invoices` tab.

Thanks for letting us know. I'll update copy
