### ISSUE TITLE
[CHORE]: Update Ditto CLI 

### ISSUE THREAD

**Issue by MorganeLecurieux** [getlago/lago-front#221]
J’ai eu Ditto, du coup!
En fait, avoir le base.json c’est la manière de faire de la version 1.1.1 de ditto cli qui datte de fin de l’année dernière
Ya moyen que tu as npx a ce moment là ça ait gardé en “cache” cette version et on a vu que npx ne check pas la last version dans ce cas (trop chelou)
Enfin bref, la version avec tous les fichiers c’est un peu la nouvelle manière de faire,
Il faudrait surement
Fixer la version en dev dependencies, comme ça on est trankil pour le future
Adapter notre app pour aller lire cette nouvelle architecture, si je me trompe pas c’est un truc un peu custom que tu as fais pour aller lire le base.json

**Comment by ansmonjol** [comment]
I guess we can close this one after https://github.com/getlago/lago-front/pull/226 have been merged @MorganeLecurieux ?
