### ISSUE TITLE
[FEAT] support darkmode colour scheme

### ISSUE THREAD

**Issue by c-nv-s** [getlago/lago-front#439]
Please allow for a user to toggle or set preference to a colour scheme with predominantly darker colours which allows for reduced eye strain when viewing in low-light environments or for extended periods of time.

**Comment by michaelponrajah** [comment]
Hello @c-nv-s, thanks for reaching out with this need!
We've built Lago based on colour themes so it can be something doable on our side. Somehow, it's still requiring research and work to make the dark-mode live and accessible. As you may know, we're focusing on core billing features first, so we'll get back to you when the topic is on our plate!

**Comment by michaelponrajah** [comment]
We're closing this issue as we're switching tool for feature requests.
Feel free to add your feedback for the team and vote here:
👉 [Dark mode - Canny](https://getlago.canny.io/feature-requests/p/lago-user-interface-support-dark-mode)
