### ISSUE TITLE
[CHORE] centralise download method in one place

### ISSUE THREAD

**Issue by ansmonjol** [getlago/lago-front#522]
Downloading an invoice is an action available multiple times in the app. Probably since this ticket have been created we're also allowed to download other type of documents.

The download logic have been duplicated but should be centralised at some point.

This ticket aims to refactor our codebase to have only one download logic written, called by every components / pages the needs it.

**Comment by ansmonjol** [comment]
Absolutely @alceil

**Comment by alceil** [comment]
@ansmonjol I bit confused on how to setup the lago front on  my machine locally. Didnt see anything about it in the docs  either. Can you point me to resources or just tell me how i can setup the project locally?

**Comment by ansmonjol** [comment]
@alceil you can follow the steps [here](https://github.com/getlago/lago/wiki/Development-Environment)

Once done, you should have all local services running in Docker.
Then you can update your code in the `front` folder on your machine and check the app running at `app.lago.dev` (default, can be changed)

**Comment by aditipatelpro** [comment]
Hi @alceil, are you still working on this issue? If not, @ansmonjol  can you assign this issue to me? 
I am interested in working on this.

**Comment by alceil** [comment]
Hey @aditipatelpro Im not working on it since i was not able to deploy it locally . @ansmonjol you can assign it to @aditipatelpro

**Comment by ansmonjol** [comment]
@aditipatelpro let me know if I can help with anything.

If you don't work on this I'll remove the assignment

**Comment by HariBhandari07** [comment]
Hi @ansmonjol I will work on this.

**Comment by HariBhandari07** [comment]
> Hi @ansmonjol, can I work on this?

Hi @ansmonjol , I have fixed this on my local machine. Since it's done in the main Lago repo, should I create a PR there?
